-- 완전한 12주 데모 데이터를 생성하려면 demo-mock-data.sql 실행 후
-- 이 파일(demo-snapshot-entries2.sql)을 실행하세요.
--
-- 현재 W49-W51 샘플이 포함되어 있으며,
-- 나머지 주차(W52-W08)는 동일한 패턴으로 추가하시면 됩니다.
--
-- 각 주차마다:
-- - 6명의 사용자
-- - 주차별 1-3개 엔트리
-- - past_week/this_week 진행상황 업데이트
-- - 협업 관계 및 리스크 포함
--
-- 실행 방법:
-- psql -h [HOST] -U [USER] -d [DB] -f demo-snapshot-entries2.sql
